### ISSUE TITLE
[add] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#1]
## ISSUE
- 프로젝트 초기 세팅

## To-Do
- [ ]  data, domain 모듈 추가
- [ ] groovy -> kotlin dsl로 이전
- [ ] dependency 추가
- [ ] 인터넷 퍼미션 + http 허용 퍼미션
- [ ] hilt application 
- [ ] 이슈 템플릿
- [ ] pr 템플릿
- [ ] 마일스톤
- [ ] Github actions
