### ISSUE TITLE
[feat] MainActivity에 BottomNavigation 추가 및 연결

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#10]
## 작업화면
<img width="200" src="https://user-images.githubusercontent.com/68374234/188797236-9db09cf5-9b72-4095-bd64-2ebc77fbebb9.png">

## ISSUE
- MainActivity에 BottomNavigation 추가 후 Home, To-Do, Profile 연결

## To-Do
- [x] MainActivity에 BottomNavigation 추가
- [x] gradle에 Jetpack Navigation 추가
- [x] HomeFragment, TodoFragment, ProfileFragment 연결
