### ISSUE TITLE
[ui] 성향 테스트 뷰 구현

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#115]
## ISSUE
- 성향 테스트 뷰 구현

## To-Do
- [ ] 성향 테스트 시작 뷰 구현
- [ ] 성향 테스트 뷰 구현
- [ ] 성향 테스트 종료 뷰 구현
