### ISSUE TITLE
[fix/feat] 규칙 수정 뷰 - item focus시 색상 변경 및 규칙 이름 수정시 반영 로직 구현

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#120]
## ISSUE
-규칙 수정 뷰 기능 수정 및 구현

## To-Do
- [ ] editText 외 부분 클릭시 softKeyBoard hide하는 로직 수정
- [ ] 규칙 이름 수정시 반영 로직 구현
- [ ] item focus시 색상 변경
