### ISSUE TITLE
[ui] 방 만들기/입장 관련 레이아웃 제작 및 화면 이동 구현

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#13]
## ISSUE
- 방 만들기/입장 관련 레이아웃 제작

## To-Do
- [x] 방만들기/입장 레이아웃
- [x] 방 이름 추가 레이아웃
- [x] 방 이름 추가 후 레이아웃
- [x] 방 코드 입력 후 레이아웃
