### ISSUE TITLE
[ui][feat] 디자인 나온 것 적용 및 방 참여 16명 초과 시 토스트 띄우기

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#134]
## ISSUE
- 디자인 나온 것 적용
- 방 참여 16명 초과 시 토스트 띄우기

## To-Do
- [x] 방 참여 16명 초과 시 토스트 띄우기
- [x] 홈 - 요일별 웰컴 메시지
     - 토요일, 일요일 로티는 추후 나오면 적용
- [x] 홈 - 아무개 그래픽
- [x] 방만들기 - 클릭 크기 효과
- [x] 알림 리스트 엠티뷰
- [x] 방만들기, 방참여 다이얼로그 - x 버튼 넣기
- [x] 탈퇴하기 - 그래픽 넣기
