### ISSUE TITLE
[ui/feat] 401 토큰 만료 처리 및 디자인 수정 사항 적용

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#141]
## ISSUE
- 401 토큰 만료 처리
- 디자인 수정 사항 적용

## To-Do
- [x] 401 토큰 만료 처리
- [x] 강제로그인 시 토큰 저장 추가
- [x] 디자인 수정 사항 적용
- [x] 방 입장 16명 초과 시 동작 확인
- [x] 하우스 탭 프로그레스 바 서버 값 넣기
- [x] 퇴사시 마이투두가 0개일 경우의 엠티뷰
- [x] 퇴사, 로그인, 탈퇴 후 스택 관리 확인 후 수정
- [x] 하우스 - 호미들 파랭이 사진 수정
- [x] 웰컴 로티 수정본 받은걸로 넣고, 주말 로티 적용
