### ISSUE TITLE
[ui] To-Do 메인 뷰 구현

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#15]
## ISSUE
- To-Do 메인 뷰 구현

## To-Do
- [x] 집 모양 asset 추가
- [x] 최상단 뷰 구현
- [x] Progress bar 구현
- [x] My to-do 구현
- [x] Our to-do 구현
- [x] 툴팁 구현
