### ISSUE TITLE
[fix] To Do 뷰 QA 반영

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#152]
## ISSUE
- To Do 뷰 QA 반영

## To-Do
- [x] 멤버별 보기 멤버 클릭시 리플 효과 변경
- [x] ToDo 60개일 때 다이얼로그 호출
- [x] ToDo 체크 박스 클릭 시 서버 통신 후 체크 반영
- [x] our to do 클릭 시 text color 검은색으로 변경되며 바텀시트 호출 
- [x] 배지 뷰 클릭 시 text 변경
- [x] todo 전체보기 클릭 시 현재 요일로 이동
- [x] member 별 보기 다른 멤버 삭제 시 상단 tab 오류 수정
- [x] todo response 값 수정
