### ISSUE TITLE
[fix] to-do 수정,추가 QA시트 

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#153]
## ISSUE
-  to-do 수정,추가 QA 반영 

## To-Do
- [x] 현재는 추가하기 버튼이 플로팅 버튼으로 공중에 떠있는데 멤버가 많아졌을 때, 가장 아래 멤버가 추가하기 버튼에 가려져서 담당자로 지정할 수 없음.(추가하기 버튼 영역을 막아두고 스크롤할 필요 있음. 추가하기 버튼 위로 20px 마진 주기. 바텀 기준 총 83px 스크롤 안 되는 영역.)
- [x] text 전부 지우면 기존 to-do명 노출 + 밑줄 비활성화 + 저장하기 버튼 비활성화(기존 to-do명 노출 X.(밑줄&비활성화는 O.))
- [x] 알림 버튼 클릭 시 on/off 확인. (on으로 default)
- [x] Todo 추가 시 60개 초과일 때 다이얼로그 호출하는 것도 추가해야 될 거 같아유
- [x] to-do 추가/수정 시 중복값 입력 불가.

**Comment by KWY0218** [comment]
@murjune 
Todo 추가 시 60개 초과일 때 다이얼로그 호출하는 것도 추가해야 될 거 같아유

todo를 추가하기 전에 다른 사람이 먼저 todo를 추가해서 60개가 될 상황이 있을 수 있기 때문임당~
`TodoLimitDialog().show(childFragmentManager, this.javaClass.name)` 요거하면 다이얼로그 호출 완료~
