### ISSUE TITLE
[feat/fix] 방참여 중 이탈 시 이슈 및 Hous- 탭 QA 수정사항 반영

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#154]
## ISSUE
- 방 참여 팝업의 '참여하기' 버튼 누르지 않은 상태에서(팝업 상태) 앱 껐다 켰을 때 "Home main view"로 진입하는 문제 해결
- Hous- 탭 QA 수정사항 반영

## To-Do
- [x] 방 코드 검색 시 state바꿔주는 부분을 -> 방 참여 팝업의 '참여하기' 버튼 누를 시 state바꿔주도록 수정
- [x] 토스트 중복 막도록 코드 수정
- [x] Hous탭 - Homies - 호미카드(회색) 클릭 시 -> "아직 성향 테스트를 하지 않은 호미예요!" 토스트 노출
- [x] Hous탭 - 우리집 별명 수정 - 수정 내역 O = 수정 이탈 팝업 / 수정 내역 X = Home main view로 이동
- [x] Hous탭 - Rules 파란 영역 클릭 시에도 화면 이동하도록 구현
- [x] 회원 탈퇴하기 워딩 수정
