### ISSUE TITLE
[fix] 2차 QA 수정

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#166]
## ISSUE
- 2차 QA 수정

## To-Do
- [ ] 배지 뷰 `<` 스크롤 영역 제외
- [ ] 성향 테스트 계산 로직 수정
- [ ] 성향 테스트 text 행간 150%로 수정
