### ISSUE TITLE
[fix/feat] 2차 QA 수정, 네트워크 연결 상태 오류 시 인터넷 연결 에러 뷰 띄우기

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#168]
## ISSUE
- 2차 QA 수정

## To-Do
- [x] 스레드에서 토스트 메시지 띄울 시 ui(메인)스레드에서 띄울 수 있도록 감싸주기
- [x] 회원가입 이후 방 생성/참여 뷰에서 뒤로가기 앱종료 토스트 띄우기
- [x] 설정 - 알림, 개인정보 및 약관, 호미나라 피드백 보내기 모두 전체 영역 클릭되도록 바꾸기
- [ ] 회원탈퇴 - '지금까지 Hous-를 이용해주셔서 감사합니다.' 문구에 Bold 처리
- [x] 회원탈퇴 - <사유 선택하기 아코디언 box>와 <의견 남기기 text 영역> 사이의 간격을 16px에서 24px로 수정
- [x] 방 생성 시 팝업 - 뒤로가기, 외부영역 클릭 시 안닫히도록 하기
- [x] 방 참여 시 팝업 - 뒤로가기, 외부영역 클릭 시 안닫히도록 하기
- [x] 방 코드 입력 시 - 잘못된 코드 입력 후 뒤로가기 이후 다시 돌아왔을 때도 에러문구 띄워져있는 현상 수정
- [x] 방 퇴사하기 - 주의 문구(방을 탈퇴하면~삭제돼요)에서 '삭제돼요!' 부분만 2번째 줄로 내려오는 것 같아요. 1줄로 해주세요!
- [x] 방 퇴사하기 - 탈퇴 전에~어떨까요? 설명 문구 행간 160% 필요.
- [x] 네트워크 연결 상태 오류 시 네트워크 에러 뷰 띄우기
- [x] 네트워크 에러 뷰 - 다시 시도하기 클릭 시 SplashState에 따라 화면 옮기기
- [x] 네트워크 에러 뷰 만들기
- [x] My to-do의 to do 이름 앞에 있는 원( - )의 크기 조정 필요.(5x5px 필요.)
