### ISSUE TITLE
[fix] 3차 QA 수정

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#180]
## ISSUE
- 3차 QA 수정

## To-Do
- [x] 방입장/생성 - text가 회색임.(블랙으로 교체 필요.)
- [x] 홈 - 코드 복사 토스트 메세지 -> '초대코드'로 변경 필요.(현재는 '참여코드')
- [x] 방 만들기, 방 입장하기 - 버튼 비활성화 방법 clickable -> enabled로 수정
