### ISSUE TITLE
[fix] 개강 업데이트 전 수정사항

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#188]
## ISSUE
- 개강 업데이트 전 수정사항

## To-Do
- [x] splash 로티 변경
- [x] 성향 테스트 후 결과 대기시간 view 2초에서 1초로 수정
- [x] 성향테스트 문항 선택 시 컬러 red 에서 blue로 수정
