### ISSUE TITLE
[feat] 방 이름 추가 / 방 코드 입력 후 다이얼로그 구현

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#19]
## ISSUE
- 방 이름 추가 / 방 코드 입력 후 다이얼로그 구현

## To-Do
- [x] 방 이름 추가 후 다이얼로그 ui
- [x] 방 코드 입력 후 다이얼로그 ui
- [x] 방 이름 추가 서버 통신 후 해당 정보로 다이얼로그 띄우기
- [x] 방 코드 입력 서버 통신 후 해당 정보로 다이얼로그 띄우기
- [x] 방 이름 추가 후 다이얼로그 - 참여 코드 복사 기능
- [x] 방 코드 입력 후 다이얼로그 - 참여하기 서버 통신
