### ISSUE TITLE
[fix] 튜토리얼 버튼 radius, 우리 집 별명 바꾸기 마진값 수정, 프로필 수정 마진값 수정

### ISSUE THREAD

**Issue by 2zerozu** [Hous-Release/hous-AOS#196]
## ISSUE
- 튜토리얼 버튼 radius, 우리 집 별명 바꾸기 마진값 수정, 프로필 수정 마진값 수정

## To-Do
- [x] 튜토리얼 버튼 radius
- [x] 우리 집 별명 바꾸기 마진값 수정
- [x] 프로필 수정 마진값 수정
