### ISSUE TITLE
[fix] Todo main 화면 아이콘 위치 변경

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#207]
## ISSUE
-  Todo main 화면 아이콘 위치 변경

## To-Do
- [x] 도움말 아이콘위치 변경
- [x] `to-do 전체보기` 버튼 제거
- [x] to-do detail로 가는 버튼 추가
