### ISSUE TITLE
[ui] Todo Detail view 구현

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#208]
## ISSUE
- Todo Detail view 구현

## To-Do
- [ ] Todo Detail view 구현
- [ ] Todo 검색 바텀시트 view 구현
- [ ] 화면 이동 연결
