### ISSUE TITLE
[feat] Todo Detail 기능 구현

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#209]
## ISSUE
- Todo Detail 기능 구현

## To-Do
- [ ] Todo detail feature 모듈 생성 및 의존성 추가
- [ ] Todo detail 관련 도메인 구현
- [ ] Todo list empty와 non-empty 구분
- [ ] 필터 관련 기능 구현
        - [ ] 요일 및 호미 정보 저장
        - [ ] 검색 결과로 나온 to do 개수
