### ISSUE TITLE
[feat] 갤러리에서 다중 사진 불러온 후, FormData 형식으로 변환

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#236]
## ISSUE
일단 비트맵 캐싱이나 [TedImagePicker](https://github.com/ParkSangGwon/TedImagePicker) 라이브러리 사용안하고, 해보도록 하겠습니다!  
실험용으로 `GalleryPracticeActivity`만들어서 테스트해볼게용~ (추후 삭제 예정)  

## To-Do
- [ ] 갤러리 접근 후 URI 불러오기
- [ ] URI Bitmap으로 변환 
- [ ] Bitmap Resizing
- [ ] Bitmap -> FormData(File형식)으로 변환
