### ISSUE TITLE
[feat] todo api screen 내에 연결

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#241]
## ISSUE
- API Videmodel 연결

## To-Do
- [ ] todo filter api 연결
- [ ] 바텀 시트 todo detail 연결
- [ ] 삭제하기 api 연결
