### ISSUE TITLE
[UI] OurRules_main 화면

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#3]
## 작업 화면  
![image](https://user-images.githubusercontent.com/87055456/187479714-aaace34a-d487-42d8-a838-8266a7f8c578.png)

## ISSUE
-TextAppearance는 일단 반영 안하구 하겠습니다~
## To-Do
- [x] OurRules_main 화면 UI 구현
- [x] BindingActivity, BindingFragment 추가
- [x] Representative_rules_item UI 구현
- [x] general_rules_item UI 구현
