### ISSUE TITLE
[ui] 대표 룰 Screen UI

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#306]
## ISSUE
- 대표 룰 Screen 및 presentation 로직. 
 
<image width = "400" src ="https://github.com/Hous-Release/hous-AOS/assets/87055456/a974b6aa-5c27-4c09-a5cb-27d7b8170476"/> 

## To-Do
- [x] 대표 룰 Screen ui 작업
- [ ] ~~rule 선택할 때 ripple 효과 지우기~~
- [x] mainRule -> 대표 룰 이동 navigation기능 추가
- [x] ruleNavGraph에 대표 룰 화면 추가
