### ISSUE TITLE
[feat] 대표 룰 수정 api 및 presentation 로직

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#308]
## ISSUE
- 대표 룰 수정 api

## To-Do
- [x] 대표 룰 수정 api
- [x] 대표 룰 수정 Usecase
- [x] 대표 룰 수정 presentation 로직
