### ISSUE TITLE
[feat/ui] rule 가이드 바텀 시트

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#320]
## ISSUE  
![image](https://github.com/Hous-Release/hous-AOS/assets/87055456/fa221328-9f44-4554-9db3-94711e95d0a9)

- rule 가이드 바텀 시트 구현하기  

## To-Do
- [x] view pager 기능 넣기
- [x] 룰 가이드 ui 구현
- [x] lottie 애니메이션 추가 (이건 디자인 나오면 추가)
