### ISSUE TITLE
[2.0.0 QA] Home + Our Rule + 룸메이트 성향 카드

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#326]
## ISSUE
- [피그마](https://www.figma.com/file/XXDlWUtyxsyAQSHZVe1ErE/Design_%EB%A6%B4%EB%A6%AC%EC%A6%88?node-id=4079%3A14568&mode=dev)
- [QA 시트](https://docs.google.com/spreadsheets/d/1CiTMTRq8CYhyaOQESJc8gEXmKAkC702JAWn9hkUEn90/edit#gid=1797783541)

# To-Do

## 우리 집 별명 수정
- [x] 라이팅 : 멤버들이 -> 다른 호미들이(요렇게 수정해 주세요! 호미들 호칭을 좀 더 익숙하게 볼 수 있도록~)

## Rules 가이드
- [x] : 룰스 고정하기~룰스 고정 어쩌구 저쩌구 사이에 있는 "Page : N"은 없어도 될 것 같아요!
- [x] : 가이드 라이팅(기획에 추가해 두었습니다! - 근데 라이팅 QA할 때 전체적으로 다시 전달 드릴 예정쓰.)

## Rules (main)
- [x] : 검색하기 -> Ruels 검색하기 
- [x] : 검색 없을 때 empty 뷰 -  현재 검색 시 일치하는 규칙 없을 때 "아직 우리 집 Rules가 없어요!" 노출.
(라이팅 상으로는 "해당되는 Rules가 없어요!"인데, 우선순위 낮은 수정 이슈입니다!)

## Rule Detail
- 이거 to-do bottom sheet에서도 마찬가지인데, to-do는 다 text data라 크게 티가 안 나는 듯!(to-do에서도 적어둘게요~)
- [x] : 피그마 디자인 상으로는 규칙 설명이 비어있는 경우, '설명 없음' 텍스트가 있는데 현재는 그 empty text가 보이지 않는 것 같습니다!

## Rules 추가 개수 제한 Dialog
- [x] : 라이팅 rule -> Rules로(2개) 바꾸면 좋을 것 같아요~
- [x] : 시도해주세요 -> 시도해 주세요(띄어쓰기!)
- [x] : 팝업 외 영역 클릭 시 닫힘.
- [x] : 뒤로 가기 시 닫힘

## Rules add
- [x] : 규칙 제목 글자수도 20자

## 룸메이트 성향 카드_A
- [x] : Max text로 자기 소개를 작성할 경우, 구분선 침범 이슈 있습니다!(슬랙 화면 공유.)
