### ISSUE TITLE
[2.0.0 QA] todo + profile + 인터넷 연결

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#329]
## ISSUE

[QA 시트](https://docs.google.com/spreadsheets/d/1CiTMTRq8CYhyaOQESJc8gEXmKAkC702JAWn9hkUEn90/edit#gid=1797783541)
[피그마](https://www.figma.com/file/XXDlWUtyxsyAQSHZVe1ErE/Design_%EB%A6%B4%EB%A6%AC%EC%A6%88?type=design&node-id=1405-8872&mode=design&t=1XMPIn8akA2knU78-0)

# To-Do Main
- [x] 현) Ruels 검색하기 -> todo 검색하기
- [x] 현) 필터 -> to-do 필터

# To-Do 필터 다이얼로그
- [x] 현) 필터 -> to-do 필터

## Todo 추가
- [x] 알림받기 text 눌러도 click 적용

## Todo 추가 제한 다이얼로그
- [x] 라이팅 : 시도해주세요 -> 시도해 주세요(띄어쓰기!)

## Todo 이탈 다이얼로그
- [x] : 라이팅 : 시도해주세요 -> 시도해 주세요(띄어쓰기!)
- [x] : (닫힘)(다른 팝업은 안 닫혀서, 통일되면 좋을 것 같습니다~)
팝업 외 영역 클릭 시 닫힘.

## Todo 삭제 확인 이탈 다이얼로그
- [x] : (닫힘)(다른 팝업은 안 닫혀서, 통일되면 좋을 것 같습니다~)
- [x] : 팝업 외 영역 클릭 시 닫힘.

## Profile - 성향테스트
- [x] : 라이팅 : 아래 내용으로 바꿔주세요!
15개 질문을 통해 나의 생활 성향을 알아보아요! (줄바꿈) 솔직한 답변은 서로를 배려할 수 있는 (줄바꿈) 좋은 기회가 될 거예요! :)

## 인터넷 연결
- [x] : 라이팅 : 확인해주세요! -> 확인해 주세요!(띄어쓰기.)
