### ISSUE TITLE
[2.0.1 Feature] 2.0.0 릴리즈 후 반영할 것들

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#330]
## ISSUE
#327

## Home main
- [ ] #327
## Rule Detail
- [ ] : 규칙a 클릭 후 규칙b 클릭 시 : a가 잠깐 나오고 b가 나오는 식으로 보여요!(슬랙 영상 참고.)
## Rules 가이드
- [ ] :  처음 Rules 보기 view에 진입했을 때 가이드 bottom sheet가 바로 뜨게끔 세팅할 수 있을까요??!(어렵다면 X!)
- [ ] : 가이드 로티를 좌우 스크롤 할 때마다 gif가 새로 시작하면 좋을 것 같습니다.(첫 번째 가이드 page 보고 있을 때 첫 로티 시작 / ...)

# To-Do 필터 다이얼로그
- [ ] 현재는 필터 요소를 누르지 않았을 때도 저장 버튼이 활성화 되어 있습니다.(우선순위 낮기 때문에 cost 많이 들면 그냥 둬도 될 듯!)

## todo 
- [ ] : 투두a 클릭 후 투두b 클릭 시 : a가 잠깐 나오고 b가 나오는 식으로 보여요!(규칙과 마찬가지 - 슬랙 영상.)

## todo - detail

![image](https://github.com/Hous-Release/hous-AOS/assets/87055456/e405c346-6815-4c0d-aa7f-34e199a75884)
