### ISSUE TITLE
[ui] 우리집 규칙 추가 ui 생성

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#36]
## ISSUE
- 우리집 규칙 추가 ui 생성

## To-Do
- [ ] 우리집 규칙 추가 View짜기  
- [ ] 우리집 규칙 Main ui id 수정
- [ ] 뒤로가기 dialog View짜기
