### ISSUE TITLE
[fix] Login api 에러별 분기처리

### ISSUE THREAD

**Issue by 2zerozu** [Hous-Release/hous-AOS#48]
## ISSUE
- Login api 에러별 분기처리

## To-Do
- [x] Login 서버 로직 기존 상태로 변경 (interface 했던거 없애기)
- [x] 404 에러시에 userInput으로 이동
- [x] 200시에 main으로 이동
