### ISSUE TITLE
[feat] 방 이름 수정하기 서버 연결

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#58]
## ISSUE
- 방 이름 수정하기 서버 연결

## To-Do
- [x] 방 이름 수정하기 서버 연결
- [x] 하우명 수정 시 기존 하우스 명 디폴트로 보이도록 설정
- [x] EditText textColorHint, line 디폴트 컬러 설정
- [x] KeyBoardUtil(EditText focus 관리) 구현 및 적용
