### ISSUE TITLE
[feat] 우리집 규칙 뷰 기능 구현

### ISSUE THREAD

**Issue by murjune** [Hous-Release/hous-AOS#7]
## 작업 화면
![image](https://user-images.githubusercontent.com/87055456/187883543-8936b5ec-3bd9-4de5-ab05-40826f857aa3.png)

## ISSUE
- 우리집 규칙 뷰 dummy 데이터로 구현
- 우리집 규칙 navigation graph 그리기   
## To-Do
- [x] 우리집 규칙 뷰 navigation graph 기초 세팅
- [x] 멀티뷰타입 enum class로 설정
- [x] 우리집 규칙 리사이클러뷰 구현
- [x] itemDecoration Util 패키지에 추가
