### ISSUE TITLE
[feat] 배지 뷰 기능 구현

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#81]
## ISSUE
- 배지 뷰 기능 구현

## To-Do
- [ ] 답변을 토대로 기능 구현하기
- [ ] 배지 리스트를 불러오는 GET API 붙이기
- [ ] 대표 배지를 설정하는 PUT API 붙이기
