### ISSUE TITLE
[feat] 알림 리스트 서버 통신 및 무한 스크롤 구현

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#86]
## ISSUE
- 알림 리스트 서버 통신 후 구현

## To-Do
- [x] 알림 리스트 어댑터 연결
- [x] 알림 리스트 서버 통신
- [x] 알림 리스트 무한 스크롤 구현
