### ISSUE TITLE
[feat] 설정, 알림 설정 기능

### ISSUE THREAD

**Issue by yjooooo** [Hous-Release/hous-AOS#98]
## ISSUE
- 설정, 알림 설정 기능

## To-Do
- [x] 설정 - 방 존재 여부에 따른 설정 뷰 이동 구현
  - 방참여/만들기 > 설정
  - 프로필 > 설정
- [x] 설정 - 개인정보 및 약관 페이지 이동 구현
- [x] 설정 - 피드백 보내기 (메일 연결) 기능 구현
- [x] 알림 설정 - 기능 구현
- [x] 프로필 > 알림 리스트 화면 이동 구현
- [x] 알림리스트 화면 뒤로가기 구현
- [x] 하우스명 수정 시 자체 뒤로가기 버튼 눌러도 다이얼로그 띄우도록 구현
- [x] 버전관리 위한 서버 요청으로 Header 추가

<div>
<img width="300" src="https://user-images.githubusercontent.com/68374234/198878142-eea4a227-893e-411d-bfe5-3471c6baa417.png"/>
<img width="300" src="https://user-images.githubusercontent.com/68374234/198878161-a3752559-ae90-4709-9392-73d723f79892.png"/>
</div>
<img width="300" src="https://user-images.githubusercontent.com/68374234/198878148-19ac76c3-5284-4065-b91f-a7cd9e81657d.png"/>
