### ISSUE TITLE
[ui] 프로필 메인 뷰 내에 오각형 구현

### ISSUE THREAD

**Issue by KWY0218** [Hous-Release/hous-AOS#99]
## ISSUE
- 프로필 메인 뷰 내에 오각형 구현

## To-Do
- [x] 프로필 메인 뷰 내에 오각형 구현
- [x] 성향 결과 별 그라디언트 추가
- [x] 배지 뷰 그라디언트 추가
- [x] theme 내에 style 추가
